# Basic site information
site_name: PyTorch Lightning Course
site_url: https://lightning-course.com
repo_url: https://github.com/marcopeix/pytorch_lightning_course.git

# Navigation
nav:
  - Home: index.md
  - Tutorials:
      - Introduction: Introduction/introduction_part_1.ipynb

# Theme: Material with dark-first palette and toggle
theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: '#AAAAAA'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: default
      primary: blue grey
      accent: '#AAAAAA'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate

# Plugins
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: true
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
  - search

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:     
      generic: true

# Custom assets
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js 

# Site‑wide variables
extra:
  version: 1.0.0
  author: Ram Surya Yenda